"""user details

Revision ID: 0b6fef22e131
Revises: 40aa33cd3fdb
Create Date: 2022-12-18 19:56:19.563196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b6fef22e131'
down_revision = '40aa33cd3fdb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('user', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('user', sa.Column('address', sa.String(), nullable=True))
    op.add_column('user', sa.Column('location', sa.String(), nullable=True))
    op.add_column('user', sa.Column('hospital', sa.String(), nullable=True))
    op.add_column('user', sa.Column('userProfile', sa.String(), nullable=True))


    # ### end Alembic commands ###


def downgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###
