version: '3.4'  # Secrets are only available since this version of Docker Compose
services:
  postgres_data:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: neurallabs
      POSTGRES_PASSWORD: neurallabs
      POSTGRES_DB: orthanc_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5432 # Map host port 5433 to container port 5432

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '9042:9042' #ngnix proxy
    depends_on:
      - orthanc

  orthanc:
    build: .
    # image: jodogne/orthanc-python:latest
    ports:
      - "4242:4242"
      - "8042:8042"
    volumes:
      - ./orthanc.json:/etc/orthanc/orthanc.json:ro
      - ./pyfilter.py:/etc/plugins/pyfilter.py:ro
      - ./libOrthancDicomWeb.so:/etc/plugins/libOrthancDicomWeb.so
      - ./libOrthancWebViewer.so:/etc/plugins/libOrthancWebViewer.so
      - ./libOrthancGdcm.so:/etc/plugins/libOrthancGdcm.so
      - ./libOrthancPostgreSQLIndex.so:/etc/plugins/libOrthancPostgreSQLIndex.so
      - ./libOrthancPostgreSQLStorage.so:/etc/plugins/libOrthancPostgreSQLStorage.so
      - ./orthanc_data:/var/lib/orthanc/db

    depends_on:
      - postgres_data

  # orthanc:
  #   build: image
  #   # image: jodogne/orthanc-python:latest #jodogne/orthanc-plugins:1.12.0
  #   command: /run/secrets/
  #   restart: always
  #   ports:
  #     - 4242:4242
  #     - 8042:8042
  #   secrets:
  #     - orthanc.json
  #   depends_on:
  #     - postgres_data
  #   volumes:
  #     # - ./main.py:/run/secrets/main.py
  #     # - ./hello.py:/etc/orthanc/hello.py
  #     # - ./orthanc.json:/etc/orthanc/orthanc.json
  #     # - ./libOrthancDicomWeb.so:/run/secrets/libOrthancDicomWeb.so
  #     # - ./libOrthancWebViewer.so:/run/secrets/libOrthancWebViewer.so
  #     # - ./libOrthancGdcm.so:/run/secrets/libOrthancGdcm.so
  #     # - ./libOrthancPostgreSQLIndex.so:/run/secrets/libOrthancPostgreSQLIndex.so
  #     # - ./libOrthancPostgreSQLStorage.so:/run/secrets/libOrthancPostgreSQLStorage.so
  #     - ./orthanc_data:/var/lib/orthanc/db
  #     # - "./auth.jsonc:/etc/orthanc/auth.json"
  #   environment:
  #     - ORTHANC_NAME=NeuralSight ORTHANC SERVER
  #     - VERBOSE_ENABLED=true
  #     - VERBOSE_STARTUP=true
  #     # - ORTHANC__PYTHON_SCRIPT="/etc/orthanc/plugin.py"
  #     - ORTHANC_PYTHON_VERBOSE=true
  #     - FILTER_MODE="filter-results"





secrets:
  orthanc.json:
    file: orthanc.json


# version: '3.5'
#
# services:
#   orthanc:
#     image: jodogne/orthanc-plugins:1.5.7
#     hostname: orthanc
#     volumes:
#       # Config
#       - ./orthanc.json:/etc/orthanc/orthanc.json:ro
#       # Persist data
      # - ./volumes/orthanc-db/:/var/lib/postgresql/data
#       - ./libOrthancDicomWeb.so:/etc/orthanc/libOrthancDicomWeb.so
#       - ./libOrthancWebViewer.so:/etc/orthanc/libOrthancWebViewer.so
#       - ./libOrthancPostgreSQLIndex.so:/etc/orthanc/libOrthancPostgreSQLIndex.so
#       - ./libOrthancPostgreSQLStorage.so:/etc/orthanc/libOrthancPostgreSQLStorage.so
        # - ./libOrthancPython.so:/etc/orthanc/libOrthancPython.so
#
#
#     environment:
#       - ORTHANC_NAME=NeuralSight ORTHANC SERVER
#       - VERBOSE_ENABLED=true
#       - VERBOSE_STARTUP=true
#       - ORTHANC_PYTHON_SCRIPT=main.py
#       - ORTHANC_PYTHON_VERBOSE=true
#
#     ports:
#       - '4242:4242' # DICOM
#       - '8042:8042' # Web
#     restart: unless-stopped
#
#   nginx:
#     image: nginx:latest
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf
#     ports:
#       - '80:80' #ngnix proxy
#     depends_on:
#       - orthanc
#
#
#   postgres_data:
#     image: postgres:latest
#     restart: always
#     environment:
#       POSTGRES_USER: neurallabs
#       POSTGRES_PASSWORD: neurallabs
#       POSTGRES_DB: orthanc_db
#     volumes:
#       - ./pgdata:/var/lib/postgresql/data
#     ports:
#       - 5433:5432 # Map host port 5433 to container port 5432
#



# https://lsb.orthanc-server.com/plugin-postgresql/5.0/libOrthancPostgreSQLIndex.so
# https://lsb.orthanc-server.com/plugin-webviewer/2.8/libOrthancWebViewer.so
# https://lsb.orthanc-server.com/plugin-postgresql/5.0/libOrthancPostgreSQLStorage.so
# https://lsb.orthanc-server.com/plugin-gdcm/mainline-gdcm3/libOrthancGdcm.so
# https://lsb.orthanc-server.com/plugin-python/debian-bullseye-python-3.9/mainline/libOrthancPython.so
