version: '3.4'

services:
  ninsight:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432

# to keep state of the db after a container is killed, these volume will maintain the data
volumes:
    postgres_data:
