version: '3.4'

services:
  ninsight:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres_db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

      # - POSTGRES_USER=postgres
      # - POSTGRES_PASSWORD=postgres
      # - POSTGRES_HOST_AUTH_METHOD=trust

    env_file:
      - .env
    ports:
      - 5432:5432


# to keep state of the db after a container is killed, these volume will maintain the data
volumes:
    postgres_data:
