apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432


          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: username
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: db_name


          volumeMounts:
            - mountPath: /var/lib/postgresql/data1
              name: postgredb-vol
      volumes:
        - name: postgredb-vol
          persistentVolumeClaim:
            claimName: postgres-pv-claim
